master/routes/web.php
<?php

Route::namespace('backend')->prefix('cpanel')->group(function(){
	Route::get('/', 'AuthController@getDashboard')->name('backend.dashboard');
	Route::resource('berita', 'BeritaController',['as' => 'backend']);
});

Route::namespace('frontend')->group(function(){
	Route::get('/','UserBeritaController@getIndex')->name('frontend.index');
	Route::get('berita/{id}','UserBeritaController@getSingle')->name('frontend.berita.details');
});

master/app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $table = 'berita';
}

master/app/Http/Controllers/backend/BeritaController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use DB;

use App\Berita;

class BeritaController extends Controller
{
    public static function uuid() {
        return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
          // 32 bits for "time_low"
          mt_rand(0, 0xffff), mt_rand(0, 0xffff),
          // 16 bits for "time_mid"
          mt_rand(0, 0xffff),
          // 16 bits for "time_hi_and_version",
          // four most significant bits holds version number 4
          mt_rand(0, 0x0fff) | 0x4000,
          // 16 bits, 8 bits for "clk_seq_hi_res",
          // 8 bits for "clk_seq_low",
          // two most significant bits holds zero and one for variant DCE1.1
          mt_rand(0, 0x3fff) | 0x8000,
          // 48 bits for "node"
          mt_rand(0, 0xffff), mt_rand(0, 0xffff), mt_rand(0, 0xffff)
        );
    }

    public function index()
    {
        $berita = Berita::select([
                            'id as id_berita',
                            'judul',
                            'isi_berita',
                            'gambar',
                            'penulis'
                        ])
                        ->paginate(16);

    	$breadcrumb = [
    		'berita' => route('backend.berita.index')
    	];

    	return view('backend.pages.berita.index',[
    		'pageTitle' => 'Cpanel - Portal Berita',
    		'breadcrumb' => $breadcrumb,
            'berita' => $berita
    	]);
    }

    public function create()
    {
    	$breadcrumb = [
    		'berita' => route('backend.berita.index'),
    		'tambah' => route('backend.berita.create')
    	];

    	return view('backend.pages.berita.create',[
    		'pageTitle' => 'Tambah Berita',
    		'breadcrumb' => $breadcrumb
    	]);
    }

    public function store(Request $request)
    {
    	$request->validate([
            'gambar' => 'required|image',
            'judul'  => 'required|max:255',
            'isi'  => 'required',
            'penulis'  => 'required|max:60',
        ]);

        try{
            DB::transaction(function() use($request){ 
                $berita = new Berita;
                $berita->id = $this->uuid();
                $berita->judul = $request->judul;
                $berita->isi_berita = $request->isi;
                $berita->penulis = $request->penulis;

                if($request->hasFile('gambar') ){
                    if($request->file('gambar')->isValid() ){
                        $file = str_slug('Berita-'.str_random(20)).$request->file('gambar')->getClientOriginalName();
                        $berita->gambar = $file;
                        $dir = './upload/files/img/berita/';
                        $request->file('gambar')->move($dir,$file);
                    }
                }
                $berita->save();
            });

            $messages = '
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              Berita Berhasil ditambah !.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>';
            return back()
                    ->withMessages($messages);
        }catch(Exception $e){
            abort(500);
        }
    }

    public function edit($id)
    {
        $berita = Berita::select([
                            'id as id_berita',
                            'judul',
                            'isi_berita',
                            'gambar',
                            'penulis'
                        ])
                        ->where([
                            'id' => $id
                        ])
                        ->first();

        $breadcrumb = [
            'berita' => route('backend.berita.index'),
            'edit' => route('backend.berita.edit',$id),
            $berita->judul => ''
        ];

    	return view('backend.pages.berita.edit',[
    		'pageTitle' => 'Cpanel - Portal Berita',
            'breadcrumb' => $breadcrumb,
            'berita' => $berita
    	]);
    }

    public function update(Request $request,$id)
    {
    	$request->validate([
            'judul'  => 'required|max:255',
            'isi'  => 'required',
            'penulis'  => 'required|max:60',
        ]);

        try{
            DB::transaction(function() use($request,$id){ 
                $berita = Berita::where([
                        'id' => $id
                    ])
                    ->first();

                $berita->judul = $request->judul;
                $berita->isi_berita = $request->isi;
                $berita->penulis = $request->penulis;

                if($request->hasFile('gambar')){
                    if($request->File('gambar')->isValid()){

                        $image = $berita->gambar;
                        $dir = './upload/files/img/berita/';
                        if(file_exists($dir.$image)){
                            unlink($dir.$image);
                        }
                        
                        $file = str_slug('Berita-'.str_random(5)).$request->file('gambar')->getClientOriginalName();
                        $berita->gambar = $file;
                        $request->file('gambar')->move($dir,$file);
                    }
                }

                $berita->save();
            });

            $messages = '
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              Berita Berhasil diupdate !;
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>';
            return back()
                    ->withMessages($messages);
        }catch(Exception $e){
            abort(500);
        }
    }

    public function destroy($id)
    {
        $berita = Berita::where([
                        'id' => $id
                    ])
                    ->first();

        $image = $berita->gambar;
        $dir = './upload/files/img/berita/';
        if(file_exists($dir.$image) && $image !=null){
            unlink($dir.$image);
        }        
        $berita->delete();

        $messages = '
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              Berita Berhasil dihapus !
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>';
        return back()
                ->withMessages($messages);
    }
}

master/resources/views/backend/pages/berita/create.blade.php
@extends('backend.layouts.app')

@push('js')
	<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
	<script>tinymce.init({ selector:'textarea' });</script>
@endpush

@section('content')
<div class="container-fluid py-5">
	<div class="container">
		<h4 class="text-primary"> Tambah Berita </h4>
		@include('backend.includes.breadcrumb')

		<div>
		<div class="container border py-3">
			@include('backend.includes.errors')
			<form action="{{ route('backend.berita.store') }}" method="post" enctype="multipart/form-data">
				{!! csrf_field() !!}
				<div class="form-group">
					<label for="gambar" class="font-weight-bold">Upload Gambar</label>
					<div class="col-6 px-0">
						<input type="file" name="gambar" id="gambar" class="p-2 border">
					</div>
				</div>
				<div class="form-group">
					<label for="judul" class="font-weight-bold">Judul Berita</label>
					<input type="text" name="judul" placeholder="Judul Berita" class="form-control form-control-md py-3">
				</div>
				<div class="form-group">
					<label for="penulis" class="font-weight-bold">Penulis</label>
					<div class="col-4 px-0">
						<select name="penulis" id="penulis" class="form-control form-control-md">
							<option>-- Penulis --</option>
							<option value="Andi">Andi</option>
							<option value="Tomi">Tomi</option>
							<option value="Andriyani">Andriyani</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="isi" class="font-weight-bold">Isi Berita</label>
					<textarea name="isi" id="isi" placeholder="isi berita ... "></textarea>
				</div>
				<div class="text-right pt-3">
					<button type="submit" class="btn btn-md btn-primary">
						<i class="fas fa-save"></i>
						Simpan
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

master/resources/views/backend/pages/berita/edit.blade.php
@extends('backend.layouts.app')

@push('js')
	<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
	<script>tinymce.init({ selector:'textarea' });</script>
@endpush

@section('content')
<div class="container-fluid py-5">
	<div class="container">
		<h4 class="text-primary"> Edit Berita </h4>
		@include('backend.includes.breadcrumb')		

		<div>
		<div class="container border py-3">
			<form action="{{ route('backend.berita.update',$berita->id_berita) }}" method="post" enctype="multipart/form-data">
				{!! csrf_field() !!}
				{!! method_field('PUT') !!}
				<div class="form-group">
					<label for="gambar" class="font-weight-bold">Upload Gambar</label>
					<div class="col-6 px-0">
						<input type="file" name="gambar" id="gambar" class="p-2 border">
						<div class="py-1">
							<img src="{{ asset('Upload/files/img/berita/'.$berita->gambar) }}" class="img-fluid">
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="judul" class="font-weight-bold">Judul Berita</label>
					<input type="text" name="judul" value="{{ old('judul',$berita->judul) }}" placeholder="Judul Berita" class="form-control form-control-md py-3">
				</div>
				<div class="form-group">
					<label for="penulis" class="font-weight-bold">Penulis</label>
					<div class="col-4 px-0">
						<select name="penulis" id="penulis" class="form-control form-control-md">
							<option>-- Penulis --</option>
							<option value="Andi" {{ $berita->penulis == 'Andi' ? 'selected' : '' }} >Andi</option>
							<option value="Tomi" {{ $berita->penulis == 'Tomi' ? 'selected' : '' }} >Tomi</option>
							<option value="Andriyani" {{ $berita->penulis == 'Andriyani' ? 'selected' : '' }} >Andriyani</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label for="isi" class="font-weight-bold">Isi Berita</label>
					<textarea name="isi" id="isi" placeholder="isi berita ... ">{{ $berita->isi_berita }}</textarea>
				</div>
				<div class="text-right pt-3">
					<button type="submit" class="btn btn-md btn-primary">
						<i class="fas fa-save"></i>
						update
					</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

master/resources/views/backend/pages/berita/index.blade.php
@extends('backend.layouts.app')

@push('js')
<script type="text/javascript">
	$(".btn-delete").click(function(){
		var judul = $(this).attr("data-judul");
		var id = $(this).attr("data-id");

		$("#judul_berita").html(judul);
		$("#btn_confirm").attr("data-id",id);
		$("#modal_delete").modal();
	});

	$("#btn_confirm").click(function(){
		var id = $(this).attr("data-id");
		if($(".delete-"+id).submit()){
			$("#modal_delete").modal('hide');
		}
	});

</script>
@endpush

@section('content')
<div class="container-fluid py-5">
	<div class="container">
		<h4 class="text-primary"> Dashboard </h4>

		@include('backend.includes.breadcrumb')
		@include('backend.includes.errors')
		<div class="text-right">
			<a href="{{ route('backend.berita.create') }}" class="btn btn-md btn-success mb-2">
				<i class="fas fa-plus-circle text-white"></i>
				Tambah
			</a>
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<th width="20%">Gambar</th>
					<th>Judul</th>
					<th>Penulis</th>
					<th width="15%">Action</th>
				</tr>
			</thead>
			<tbody>
				@forelse($berita as $b)
				<tr>
					<td>
						<img src="{{ asset('upload/files/img/berita/'.$b->gambar) }}" class="img-fluid">
					</td>
					<td>{{ $b->judul }}</td>
					<td>{{ $b->penulis }}</td>
					<td>
						<a href="{{ route('backend.berita.edit',$b->id_berita) }}" class="btn btn-sm btn-success">
							<i class="fas fa-pencil-alt mr-2 text-white"></i>
							edit
						</a>
						<form class="delete-{{ $b->id_berita }}" action="{{ route('backend.berita.destroy', $b->id_berita) }}" method="POST">
							{!! csrf_field() !!}
							{!! method_field('DELETE') !!}
				       	 	<button type="button" class="btn-delete btn btn-danger btn-sm mt-2" data-judul="{{ $b->judul }}" data-id="{{ $b->id_berita }}">
				       	 		<i class="fas fa-trash"></i>
				       	 		hapus
				       	 	</button>
				    	</form>
					</td>
				</tr>
				@empty
				<tr>
					<td colspan="4"> <h5>Berita Kosong</h5></td>
				</tr>
				@endforelse
			</tbody>
		</table>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="modal_delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Hapus Data <span id="judul_berita"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<p>
      		Apakah anda yakin ingin menghapus data ini ?
      	</p>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Batal</button>
        <button type="button" id="btn_confirm" class="btn btn-success px-4" data-id="">Ya</button>
      </div>
    </div>
  </div>
</div>
@endsection